# Ordered by output of `jazzy --help config`

output: docs
clean: true
sdk: iphonesimulator
author: ArcBlock
author_url: https://arcblock.io
module: ABSDKCoreKit
github_url: https://github.com/ArcBlock/arcblock-ios-sdk
github_file_prefix: https://github.com/ArcBlock/arcblock-ios-sdk/tree/master
exclude:
  - ABSDKCoreKit/ABSDKPagination.swift
module_version: 0.9.4
