excluded:
  - Pods
  - Carthage
  - Example
  - Templates
  - ArcBlockSDK/ABSDKWalletKit/protobuf
  - ArcBlockSDK/ABSDKCoreKit/ed25519swift
  - ArcBlockSDK/ABSDKCoreKit/Multibase

line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
