language: swift
osx_image: xcode9.3
cache:
  cocoapods: true
  directories:
    - /home/travis/.rvm/
    - $HOME/Library/Caches/Homebrew
before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - pod repo update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - pod install
  - xcodebuild -scheme ABSDKCoreKit -workspace ArcBlockSDK.xcworkspace -sdk iphonesimulator11.3 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty -c
  # - xcodebuild -scheme ABSDKAccountKit -workspace ArcBlockSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty -c
  # - xcodebuild -scheme ABSDKMessagingKit -workspace ArcBlockSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty -c
  # - xcodebuild -scheme ABSDKWalletKit -workspace ArcBlockSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty -c
  - swiftlint
notifications:
  email: false
