language: swift
osx_image: xcode9.3
cache:
  directories:
  - $HOME/travis/.rvm/
  - $HOME/Library/Caches/Homebrew
  - Carthage
branches:
  only:
  - master
before_install: make travis-init
script: make travis
notifications:
  email: false
before_deploy: make travis-deploy
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Mp7Qpifvd9yu17obFksWEA4DsMQlU68p+MGsNG9G678+msA6S/ioDASRA/6a0GDzWBFsTWniyxnky6ZzkK9ZvP3g4Wl9LszEb97RCY9TEOCKDz5cuscv5rwy0cC/k9zbD1Dp225/GakYz3mvjOcodTI9ww5b8qv/mXPeV5bvtESG0NuzrCouu4eYGRf0+f0JB4h76sMS1VK4vovSEPobWsbFNpRUM9E/oVBilplzSQnvhLyTl6ukdVsJzudUAKgAWJjD6ZgkNLK74gv2U3wtWv9KoXfQkOw6QGLfyANbx57U0LUXlG7G/2NNJXujUpfUe6Pj7JSytjLG7kTYelXAEkcGtIK+kz5QP3y2M8kzFcc257yf5WnlY15YPdhR1QiP5dZ/OBiPBAHELdH7qYniGwCTrW2Ts+pCiqjwWMT8KkYxqrBKBqplFjLF302A2AwYmjNjtj4L1C/7nJGF5P8BUvhjk5mE3QigS5/T5Q8fefeRD2k/Ej6UrRTDCu1SpNr/p0Y/Ug3gbNGnTKwA4qzD3/XHqzt+PcPhUjW97nRa6bjPpDKiHPzYsCRkKcsM3v4ouxgyxRm01PPRwcvWo7GmVa923ljj9kQtYOWNyVdD3DKR2u3ulimwUhxzmQiMecpqvKtCNGugvQCgkXV+t+oLeMPf3LAClF8tW0l5slwU+KM=
  file: build/ArcBlockSDK.zip
  on:
    repo: ArcBlock/arcblock-ios-sdk
    branch: master
env:
  global:
    secure: TqBebel7XBse4ATMMNKgJQjfroQBOAaEp2Q81l5vPiXVlI04SvG5187v0MtnuVwh+hM3t9wWTw+WqhV2z5cRWN4gIe9AdTPcSEu5kptTaKIKcJuxjon+M42hNjQiKwM+m8+LgW396yay9ZH+8ndhZyYYJc62AuYDkOe/OL402aQNRHfwA2Jibd6IjaAUr0ZASInfK/OTPwsUCOfgz8eD9mUhqAiS5UrcmuD0/sr+rqw/35HgRGH3RwCc63lx7G2DsTCP3x2XzchKPDXpUGQg+0NWi45hTeUl4lfnbPm6trH6ujDIht+Kn9+TuknJKfuIaIgZVnhDgLgnRYrL/BSoSn6YYOb5xQaDf4JUt7WVZeBKV58BIqbN0GTzqCzHZ01BsykvynA+iRbx2aHBf0oAvnBVRxcYMq2uoxR2KTBUoC1taHTIsGhq0WJa5mJvDszUv2H0I9lcolCnbZVZ1vyhrZey9boGdcxLdbh/uWWZCJwhTTNWbwAzXltcdtu/gcbMxUd10R1mB88Zza1f2cuEpZu44AcEi2uKJWit+30ArkRZKLwZgY1qRkeAtp37hgSlSrXL5kj8CbzCYdvW8OQXwE9MTw6heZvfSHKgqucUrkUrFGKvk5/4j/zzL4Npa38lJIf1ZY3LnyxWlX8XXMVC38x3CoI2yvgoR/q3zlfmppo=
