project 'RichestAccounts.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RichestAccounts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RichestAccounts
  pod 'ArcBlockSDK', :path => '../../'
  pod 'Apollo', :git => 'https://github.com/ArcBlock/apollo-ios.git'

  target 'RichestAccountsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RichestAccountsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
