# Ordered by output of `jazzy --help config`

output: ../docs/ABSDKWalletKit
clean: true
objc: true
umbrella_header: ABSDKWalletKit.h
framework_root: .
sdk: iphonesimulator
author: ArcBlock
author_url: https://arcblock.io
module: ABSDKWalletKit
github_url: https://github.com/ArcBlock/arcblock-ios-sdk
github_file_prefix: https://github.com/ArcBlock/arcblock-ios-sdk/tree/master/ABSDKWalletKit
skip_undocumented: true
hide_documentation_coverage: true
