# Ordered by output of `jazzy --help config`

output: ../docs/ABSDKAccountKit
clean: true
objc: true
umbrella_header: ABSDKAccountKit.h
framework_root: .
sdk: iphonesimulator
author: ArcBlock
author_url: https://arcblock.io
module: ABSDKAccountKit
github_url: https://github.com/ArcBlock/arcblock-ios-sdk
github_file_prefix: https://github.com/ArcBlock/arcblock-ios-sdk/tree/master/ABSDKAccountKit
skip_undocumented: true
hide_documentation_coverage: true
