# Ordered by output of `jazzy --help config`

output: ../docs/ABSDKMessagingKit
clean: true
objc: true
umbrella_header: ABSDKMessagingKit.h
framework_root: .
sdk: iphonesimulator
author: ArcBlock
author_url: https://arcblock.io
module: ABSDKMessagingKit
github_url: https://github.com/ArcBlock/arcblock-ios-sdk
github_file_prefix: https://github.com/ArcBlock/arcblock-ios-sdk/tree/master/ABSDKMessagingKit
skip_undocumented: true
hide_documentation_coverage: true
