name: Code Coverage

# 当提交不需要打版本的commit时，只需要不bump version，则后续fastlane action不会触发

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codecov:
    container:
      image: swift:5.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-test-discovery --enable-code-coverage
      - uses: mattpolzin/swift-codecov-action@0.7.3
        with:
          MINIMUM_COVERAGE: 50
          INCLUDE_TESTS: "true"
