name: Code Coverage

# 当提交不需要打版本的commit时，只需要不bump version，则后续fastlane action不会触发

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Start Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Test coverage
      uses: maxep/spm-lcov-action@0.3.0
        with:
          output-file: ./coverage/lcov.info