name: Code Coverage

# 当提交不需要打版本的commit时，只需要不bump version，则后续fastlane action不会触发

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Start Coverage Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependency
        run: |
          bundle install
          pod install
      - name: Run tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: ArcBlockSDK.xcworkspace
          sdk: iphonesimulator
          destination: "platform=iOS Simulator,name=iPhone 8"
          configuration: Debug
          scheme: ArcBlockSDK
          derived-data-path: ./output
          action: test
          enable-code-coverage: true
      - name: Generate Coverage Report
        run: |
          fastlane code_coverage
      - name: Comment PR
        uses: machine-learning-apps/pr-comment@master
         env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          path: cov_reports/report.md
